username: chinmayee.s@cognosos.com
password: Prosight123
name: chinmayee.s@cognosos.com
idToken: >-
  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmoiOiI1NXptcEphMlE3dnlqdWxORjcySks2IiwiaWF0IjoxNzY1OTc1MTIwLCJleHAiOjE3NjYwNjE1MjAsImF1ZCI6IkxvX2xuVXhGTDNadk1uRk41ZU1qRmlDVXYxeEZxRi1IIiwiaXNzIjoiaHR0cHM6Ly9kZXYtY294LWhlYWx0aC1pbWFnaW5lLWFwaS5sZXZlcmVnZS5jb20iLCJzdWIiOiI2QmE2VW1HTVZHb0R4dnhFbnVoVHFpIn0.E8ic5ehToSNasIA9CXgOepE_8VAB6pb5-zMwHPVLt9Q
SECRET: >-
  4tyGsPDHZ6JZA5HPPBTA3c2O2mQYSiRpT3EcbHwPlcEr2FwgaNEGZuhmoJbdHkEK8U6eDtmPpxwZth1CzLCFPsnc
API_KEY: 07ytMWNK8NtT03Ue2VKHUk
PROJECT_ID: 55zmpJa2Q7vyjulNF72JK6
SYSTEM_ID: 1WZp0PBZ2Y9BB5nYWnaDmx
API_Base_URL: https://dev-cox-health-imagine-api.leverege.com/v1
hsptlBluePrintID: 2I8n67xzYK0lHliPLeJMih
API_Lev_URL: https://dev-cognosos.web.app/
ENVIRONMENT_BLUEPRINT_ID: 1DK2wgfK84rv5ja7todNTL
ASSET_BLUEPRINT_ID: 5fauRxVdghMnOTwbFKkgTB
STAFF_BLUEPRINT_ID: 6m7smeRtSJ9AYW16KOGbWH
levidToken: >-
  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjU5MDMzNDQsImV4cCI6MTc2NTk4OTc0NCwiYXVkIjoiTG9fbG5VeEZMM1p2TW5GTjVlTWpGaUNVdjF4RnFGLUgiLCJpc3MiOiJodHRwczovL2Rldi1jb3gtaGVhbHRoLWltYWdpbmUtYXBpLmxldmVyZWdlLmNvbSIsInN1YiI6IjRHMU9WU3k0VkkybVhZT2lOc0h3b2oifQ.3_0zXJJx5ZN1v5hB_oUO3l9XYMv410wmK9zSU1VsnEE
rentaltimerID: 6s4iOs96fVWmAE2tCMcrD7
maintenancetimerID: 3aG2kXeninOgoWUYtuMn99
OLGHospitalDetails:
  hospitalName: Oschner Lafayette General1
  hospitalID: 0qsdrAwPwozPnYptvlWL0d
  rentalIncID: 0K5pz4MjIP0B9im7T1plOb
  maintenance: 0hBoKLjLENTpLvkCbGRQEz
  tagLow: 0pDvBn1mrxExBfScw00akC
