username: chinmayee.s@cognosos.com
password: Prosight123
idToken: >-
  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmoiOiI1NXptcEphMlE3dnlqdWxORjcySks2IiwiaWF0IjoxNzY1MTk3ODEyLCJleHAiOjE3NjUyODQyMTIsImF1ZCI6IkxvX2xuVXhGTDNadk1uRk41ZU1qRmlDVXYxeEZxRi1IIiwiaXNzIjoiaHR0cHM6Ly9kZXYtY294LWhlYWx0aC1pbWFnaW5lLWFwaS5sZXZlcmVnZS5jb20iLCJzdWIiOiI2QmE2VW1HTVZHb0R4dnhFbnVoVHFpIn0.LNDLYtG-fp6Y-wlCLnjiYL_g2_fGSz6z-i49kGmr68s
SECRET: >-
  4tyGsPDHZ6JZA5HPPBTA3c2O2mQYSiRpT3EcbHwPlcEr2FwgaNEGZuhmoJbdHkEK8U6eDtmPpxwZth1CzLCFPsnc
API_KEY: 07ytMWNK8NtT03Ue2VKHUk
PROJECT_ID: 55zmpJa2Q7vyjulNF72JK6
SYSTEM_ID: 1WZp0PBZ2Y9BB5nYWnaDmx
API_Base_URL: https://dev-cox-health-imagine-api.leverege.com/v1
hsptlBluePrintID: 2I8n67xzYK0lHliPLeJMih
API_Lev_URL: https://dev-cognosos.web.app/
ENVIRONMENT_BLUEPRINT_ID: 1DK2wgfK84rv5ja7todNTL
ASSET_BLUEPRINT_ID: 5fauRxVdghMnOTwbFKkgTB
STAFF_BLUEPRINT_ID: 6m7smeRtSJ9AYW16KOGbWH
