username: chinmayee.s@cognosos.com
password: ean8VCF-ezd7gnb5fen
idToken: >-
  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmoiOiIwSDhFYW5RMEdlZmNPWVJqVjQ2d0w5IiwiaWF0IjoxNzY1NTIyMDYwLCJleHAiOjE3NjU2MDg0NjAsImF1ZCI6Ijk1NzhlMDQ2MGM5OGQ0YWRjMGY4N2Y3MCIsImlzcyI6Imh0dHBzOi8vc3RnLWNveC1oZWFsdGgtaW1hZ2luZS1hcGkubGV2ZXJlZ2UuY29tIiwic3ViIjoiMXVNU1FEdXpTS1B3S2ZTd2d0RjhPMSJ9.1Z4ms4cpHCAp2YMjvAy-AtzcK-H9twXWvrCdCUxZgIU
SECRET: >-
  2VX72HtkbJs28Gg3ES0YtD3fkEP2scJVmizM16ejaPMP72f4SePQSU249Orbtavub438gTycuZgyMQ4ApXIX2Mn0
API_KEY: 3XckzCuBn5yVE5jLRDinPx
PROJECT_ID: 0H8EanQ0GefcOYRjV46wL9
SYSTEM_ID: 23fqm29hl188zLLfhodrp9
API_Base_URL: https://stg-cox-health-imagine-api.leverege.com/v1
hsptlBluePrintID: 2I8n67xzYK0lHliPLeJMih
buildingId: 4sqr23Qxh8tjYlBKpCVPEI
API_Lev_URL: https://stg-cognosos.web.app/
ENVIRONMENT_BLUEPRINT_ID: 2aYsKxhEzCh4YiQtqQaiEH
STAFF_BLUEPRINT_ID: 061swuouJPptKewstsMPH8
ASSET_BLUEPRINT_ID: 1j5mDeWg8XtoipEYHdbmD4
